# Generated by Django 5.0 on 2025-05-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='delivery_method',
            new_name='remainder_method',
        ),
    ]
