# Generated by Django 5.0 on 2025-05-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_rename_delivery_method_reminder_remainder_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='remainder_method',
            new_name='reminder_method',
        ),
    ]
